### ISSUE TITLE
As a broadcaster, I want to change my channel visibility, so that I can control who can access at a specific time

### ISSUE THREAD

**Issue by e7d** [e7d/neap#15]
Add the ability to flag a channel visibility:
- `public`: anyone can join
- `password`: anyone knowing the challenged password can join
- `subscribe`: only subscribers can join
- `password+subscribe`: anyone knowing the challenged password can join, subscribers can join directly

Given that, channel and stream information stays publicly available but RTMP, HLS and Dash access to the live stream gets limited.

**Comment by tgd1973** [comment]
Hello! Very interesting, but I would like to know if you can install on an OS. Centos (with the appropriate commands manuals for installation)?
