### ISSUE TITLE
Problem with first start

### ISSUE THREAD

**Issue by twister5800** [e7d/neap#29]
Hi and thanks for doing this :-)

I end up with this line after running "vagrant up":
==> Neap: /tmp/vagrant-shell: line 1: /vagrant/bootstrap.sh: Permission denied

If i visit http://neap.dev i just get the nginx welcome page?

Reagards
Martin

**Comment by twister5800** [comment]
just did chmod 777 on bootstrap.sh and vagrant reload, that did remove the error
but i still get nginx start page, should there not be a web interface for neap?

**Comment by twister5800** [comment]
![image](https://user-images.githubusercontent.com/13104344/27759672-7773144c-5e36-11e7-91b2-0914b0ae3b70.png)

**Comment by twister5800** [comment]
okay did chmod 777 * in /bootstrap and the installer completed without errors, but still no web interface, just default nginx:

![image](https://user-images.githubusercontent.com/13104344/27760194-e71cf398-5e41-11e7-90af-2960532d7cd5.png)

what to do from here?

**Comment by e7d** [comment]
Hey.

Thanks for trying out Neap, even if the project has been lagging for a few months now...

Regarding your issue, the first thing is you shouldn't have that blank page.

I first need to know from which branch or version you started up.
Then you seem to have an early rights error on bootstrap time, when the script tries to setup a data disk in the project directory. It fires an error when the newly created disk is about to be mounted inside the Virtual Machine, preventing all the rest of the bootstrapping to be achieved.

That would instantly make me think that the virtual disk we try to attach was never actually created beforehand.

It should reside at neap/.vagrant/machines/neap/virtualbox/data.vdi

First, check if it exists and we'll see from there.

**Comment by e7d** [comment]
I just want to previse that Neap is still a far-from-finished work-in-progress project.

If you want something working out of the box, you should try my legacy release "Media Streaming" : https://github.com/e7d/neap/releases/tag/legacy-1.0.0

You even have an OVA and a documentation sitting next to the sources archives.
If you need to access the virtual machine use `streaming` as user and password. Then you can go root with `sudo`.

**Comment by twister5800** [comment]
Hej Michael,

Thanks for your reply ☺

Okay when it’s because NEAP is not finish yet, I can understand why I cannot make it work ☺

I already use your LEGACY streaming server for out Drone streaming at the volunteer firedepartment and I love it ☺

Sadly I cannot update (apt-get upgrade), as when I do that, apache stops responding ☺

Thanks for all this.

Best regards Martin and I look forward to Neap being finished, you are a very skilled programmer!!!

Fra: Michaël Ferrand [mailto:notifications@github.com]
Sendt: 1. juli 2017 14:01
Til: e7d/neap <neap@noreply.github.com>
Cc: Martin Lindemann Frederiksen <martin@mlf.dk>; Author <author@noreply.github.com>
Emne: Re: [e7d/neap] Problem with first start (#29)


I just want to previse that Neap is still a far-from-finished work-in-progress project.

If you want something working out of the box, you should try my legacy release "Media Streaming" : https://github.com/e7d/neap/releases/tag/legacy-1.0.0

You even have an OVA and a documentation sitting next to the sources archives.
If you need to access the virtual machine use streaming as user and password. Then you can go root with sudo.

**Comment by twister5800** [comment]
Hi again,

Using your ova I can update everything, so please disregarding that issue.

Have a nice weekend ☺

Best regards
Martin

Fra: Martin Lindemann Frederiksen
Sendt: 1. juli 2017 19:16
Til: 'e7d/neap' <reply@reply.github.com>
Emne: SV: [e7d/neap] Problem with first start (#29)

Hej Michael,

Thanks for your reply ☺

Okay when it’s because NEAP is not finish yet, I can understand why I cannot make it work ☺

I already use your LEGACY streaming server for out Drone streaming at the volunteer firedepartment and I love it ☺

Sadly I cannot update (apt-get upgrade), as when I do that, apache stops responding ☺

Thanks for all this.

Best regards Martin and I look forward to Neap being finished, you are a very skilled programmer!!!

Fra: Michaël Ferrand [mailto:notifications@github.com]
Sendt: 1. juli 2017 14:01
Til: e7d/neap <neap@noreply.github.com<mailto:neap@noreply.github.com>>
Cc: Martin Lindemann Frederiksen <martin@mlf.dk<mailto:martin@mlf.dk>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Emne: Re: [e7d/neap] Problem with first start (#29)


I just want to previse that Neap is still a far-from-finished work-in-progress project.

If you want something working out of the box, you should try my legacy release "Media Streaming" : https://github.com/e7d/neap/releases/tag/legacy-1.0.0

You even have an OVA and a documentation sitting next to the sources archives.
If you need to access the virtual machine use streaming as user and password. Then you can go root with sudo.
