### ISSUE TITLE
media-streaming-1.0.0.ova credentials

### ISSUE THREAD

**Issue by tgd1973** [e7d/neap#9]
Hello! I was able to download your distro from here http://pub.nkosi.org/media-streaming/ and I would have to make the system user pass the test.

 Thanks a lot

**Comment by e7d** [comment]
Hey,

media-streaming-1.0.0.ova is an old release, that you found on an unofficial mirror I had no idea existed. This _virtual box_ is clearly deprecated.

This first version was more a draft than a real real project at the time, containing a whole collection of different issues. I would not be maintaining this actively, since I'm now working on **Neap**, the next generation of **Media Streaming**.

That being said, and if you are comfortable with tools like vagrant, you can try and clone the [legacy branch](https://github.com/e7d/neap/tree/legacy). It already contains some fixes of issues I found on _media-streaming-1.0.0.ova_.

**Comment by e7d** [comment]
Regarding what you address:

> I would have to make the system user pass the test.

I don't really understand what you mean by that. Please try to be more specific and I'll see what I can do for you.

**Comment by tgd1973** [comment]
media-streaming-1.0.0.ova   is a container for VirtualBox ... when it loads the operating system in the VirtualBox ...  for login into virtualzed sistem, du need a user / pass ... EXAMPLE user: root,  but the password is ?

**Comment by e7d** [comment]
The credentials are available in the description of the box. You should login using the _streaming_ user and also _streaming_ as password. Starting there, you can use the **sudo** command to access root.

**Comment by tgd1973** [comment]
The problem is that from where I downloaded there is no description ...

**Comment by e7d** [comment]
That would explain it.

**Comment by tgd1973** [comment]
Ok user /pass is : streaming . 
Thank you for now ... Further I'll try to install the version from the legacy

**Comment by tgd1973** [comment]
Excuse me again ... first on its website there was documentation that now no longer visible on how to use the app. Please can give me a link or something else to see it?

Thanks again.

**Comment by tgd1973** [comment]
Hello! I tested  .ova image and is  fully functional ...  missing options for accounting to ensure's rights of who can record the live channels, the embed codes for live/records streaming players, and the possibility to delete movies recorded but not useful...
I saw in developing, here on Git that a future version has already implemented some of these options ... I can install? On what system? In the future it will be possible to install on systems like Centos?
For me it would be very helpful because I can put on centos, even, a control panel like Kloxo that can install only on centos.
Thank you very much .

**Comment by e7d** [comment]
Hey again!

Yes a new version is in development, and no, it's not operational yet, and it will not be in a short future, as the new project is in its early days. I can't even give you a date, as I'm working on this project on my personal time.

Also, you should understand this new project will only be a streaming "server", meaning no GUI will be included in it. This will be part of another project I'll start at a later time, when I'll judge the server functional enough.

For the time being, you'll have to deal with "Media Streaming".

**Comment by tgd1973** [comment]
But if the new project (I saw in branch: develop) which already includes a database ... what's the use?
Then how it intends to protect the button to record the illegal use of potential visitors? Clicking too many times on the record may fill the temp folder or otherwise stop a recording in progress, or even lock the server for too many concurrent processes ffmpg ...

**Comment by e7d** [comment]
Please, you need to read me. I'm trying to explain you there is too separate projects.

The one you use is an old draft, and I will do nothing about it. You can use it as it is, or try to improve it your self.

The **new** project is not yet functional and will not be before month. You saw a database, yes, and it's working. But this is a work in progress, and the API itself is at its very start. I'm sorry but I will not provide any support until I push something to **master**. Until then, you'll have to wait.

**Comment by tgd1973** [comment]
Excuse me but I have not expressed well ... For everything I said in the last two Messages ... I was referring only to the project under development (not to old project that I understood for some previeus message that ... is no longer available).

**Comment by e7d** [comment]
And again, i refer you to the last part of my last message.

> The new project is not yet functional and will not be before month. You saw a database, yes, and it's working. But this is a work in progress, and the API itself is at its very start. I'm sorry but I will not provide any support until I push something to master. Until then, you'll have to wait.

**Comment by tgd1973** [comment]
In reference to the project in development I wrote some Suggested / request  to e-mail:  mail@e7d.io  ... Kindly if you can reply to me.
Thanks again .

**Comment by tgd1973** [comment]
Hello! Would like to know if this latest version of  Nginx media-streaming server can be installed on other systems like Centos or Ubuntu and if possible to install without using Vagrant?
Any predictions for the first release?
Thank you very much .
